マウススクロールでカメラズーム
projectrabbit010/AutoAnt pull request #1
Opened 2019-05-25 13:58 UTC by Miyakomb

2019-05-26 05:13 UTC, gif-hara requested changes
結構把握してくれてありがたみ 🙏 
マウスホイール移動量周りを修正してくれればマージしてもOK 🙆

2019-05-26 05:13 UTC, hiroki-kitahara commented on Assets/HK/AutoAnt/Scripts/GameControllers/InputActions/Elements/ScrollToZoomCamera.cs
> +            // FIXME: ドラッグ移動量をオプションか何かで編集出来るように
```suggestion
            // FIXME: ズーム移動量をオプションか何かで編集出来るように
```

2019-05-26 05:13 UTC, hiroki-kitahara commented on Assets/HK/AutoAnt/Scripts/Input/Events.cs
> +            public static ScrollData Get(int directionId)
[IMO]
`id`よりもマウスホイール移動量で良いような気がする
スマホ操作ならピンチインの時に正の値、ピンチアウトで負の値というイメージ

2019-05-26 05:13 UTC, hiroki-kitahara commented on Assets/HK/AutoAnt/Scripts/Input/Updaters/Standalone.cs
> +                // FIXME: ダサい
[IMO]
ここも`direction`(`Id`?)に変更するより、マウスホイール移動量でよさげ。

2019-05-26 05:14 UTC, hiroki-kitahara commented
せめてこのPRによってどんな変化があるかを説明文に記入してくれるとありがたい 🙏 
PRフォーマットあとで考える 🤔

2019-05-28 13:45 UTC, Miyakomb commented
移動量そのまま使うように変更しやした。

2019-05-28 13:49 UTC, gif-hara approved these changes
🙆 👍

2019-05-28 13:49 UTC, merged