農業のモデル関係更新
projectrabbit010/AutoAnt pull request #100
Opened 2019-07-16 15:30 UTC by Miyakomb

## 変更点概要
- 農業のモデルを購入したやつに差し替え（仮）

## 依存するPR（先にマージする必要のあるPR）
- 🍐

## 特に見てほしい箇所
- 収穫可能のときにアイコンがちゃんと出るか

## 特に見なくていい箇所
- 🍐

## その他
- 🍐

2019-07-18 11:34 UTC, hiroki-kitahara commented
`Assets/HK/AutoAnt/DataSources/CellEvents/Facility/101000.asset`のGimmickPrefabがMissingになっているからエラー出てる 😭 
マスターデータを再度ダウンロードすれば治るはずなので確認シャス

2019-07-24 14:24 UTC, Miyakomb commented
対応しまいた

2019-07-24 14:27 UTC, gif-hara approved these changes
OK 🙆

2019-07-24 14:28 UTC, hiroki-kitahara commented
と思ったらアイテム吹き出し出てない 😭

2019-07-24 14:30 UTC, hiroki-kitahara commented
しかもプレハブ見たらMissingになっている・・・？ 🤔 
<img width="751" alt="スクリーンショット 2019-07-24 23 29 36" src="https://user-images.githubusercontent.com/5396546/61802134-f0216e80-ae6a-11e9-85f5-13d668ff6bfb.png">

2019-07-24 14:30 UTC, Miyakomb commented
なぞ。みる。

2019-07-24 14:31 UTC, Miyakomb commented
最初から壊れてたくさいな。手順ミスったかなー。対応します

2019-07-24 14:57 UTC, Miyakomb commented
FacilityBase作るって言ってた流れでちゃんと作ったのにアップせずチェックアウトして消えてたってオチでした

2019-07-24 14:59 UTC, hiroki-kitahara commented
コンフリクトしてる・・・！

2019-07-24 14:59 UTC, Miyakomb commented
違う場所にコミットしていた・・・？

2019-07-24 15:02 UTC, Miyakomb commented
なんかしらんけどご丁寧にFacilityBaseだけ別ブランチで上げててそっちはもうマージ済みらしい。汎用的なベースだから独立させたのかなあのときの俺は

2019-07-24 15:03 UTC, Miyakomb commented
ちょっとまって整理するから

2019-07-24 15:05 UTC, hiroki-kitahara commented
```
$git merge master
$git checkout --theirs .
```
脳死でこれでも良いかも？

2019-07-24 15:05 UTC, Miyakomb commented
1. 今さっきFacilityBaseを追加したコミットをRevert
2. https://github.com/projectrabbit010/AutoAnt/pull/99 これをrestore branch
3. restoreしたブランチをdata/update_facility_modelsにマージ
4. 参照系調整してコミット

でいい？

2019-07-24 15:06 UTC, Miyakomb commented
あーマスターをね。そっちでやりまーす

2019-07-24 15:18 UTC, Miyakomb commented
これで完璧なはず

2019-07-24 15:27 UTC, gif-hara requested changes
`CellEvent.Facility.000` `CellEvent.Facility.001` ともに `FacilityBase`を継承していないので再度確認をシャス 🙏

2019-07-24 15:41 UTC, Miyakomb commented
![image](https://user-images.githubusercontent.com/15090220/61807620-d84ee800-ae74-11e9-80e7-b563fed46f1e.png)
`CellEvent.Facility.000`に関しては仮モデルって割り切って対応してなかったけどしたほうがいい？
あと`CellEvent.Facility.001`はちゃんとベースになってる気がするんだけどこういうことじゃない？

2019-07-24 15:47 UTC, hiroki-kitahara commented
あるえ

2019-07-24 15:48 UTC, hiroki-kitahara commented
一回ブランチ切り替えたら治った・・・！

2019-07-24 15:48 UTC, gif-hara approved these changes
OK 🙆

2019-07-24 15:48 UTC, merged